name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker image
      run: |
        docker build -t ulloazhector/docker-graphql:0.0.2 .
        docker build -t ulloazhector/docker-graphql .
      
    - name: Push Docker image
      run: |
        docker push ulloazhector/docker-graphql:0.0.2
        docker push ulloazhector/docker-graphql
        
        
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
